# Generated by Django 3.1 on 2020-08-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NastyGalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product Title', max_length=200)),
                ('original_price', models.CharField(help_text='Original Price', max_length=200)),
                ('sale_price', models.CharField(help_text='Sale Price', max_length=200)),
            ],
        ),
    ]
